name: voiceclone
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.11
  - pytorch=2.2.2
  - torchaudio=2.2.2
  - ffmpeg
  - llvm-openmp
  - "numpy<2"
  - pip
  - pip:
      - coqui-tts==0.27.0
